---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: grafana
data:
  grafana.ini: |
    [log]
    mode = console
    evel = info
    [paths]
    data         = /var/lib/grafana/data
    logs         = /var/log/grafana
    [security]
    admin_user   = admin
    admin_password = admin